### ISSUE TITLE
Error getting data: Failed to connect to locahost; 9001:1433 - getaddrinfo ENOTFOUND localhost, 9011

### ISSUE THREAD

**Issue by m4ss1m0g** [R0tenur/visualization#20] opened 2020-09-25 20:18 UTC
## Expected Behavior
Show the Schema

## Current Behavior
Pop up an error

## Possible Solution
Remove default port (1433) from the connection.
I suspect there are a default port 1433 on the connection the error says `Failed to connect to locahost; 9001:1433`
9001 is the port where my SQL listen.

## Steps to Reproduce
1. Install a SQL Server instance on port 9001 or
2. With docker launch `docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssw0rd!" -e "MSSQL_AGENT_ENABLED=true" -p 9001:1433 --name sql1 --hostname sql1 mcr.microsoft.com/mssql/server:2019-latest`
2. Launch the Schema Visualization

## Other
Cannot copy/click the link on the error message

## Attached 
I attach the image of the error
![Screenshot 2020-09-25 221656](https://user-images.githubusercontent.com/4323707/94312258-d7d04680-ff7c-11ea-9907-db526948ca9a.png)

**Comment by R0tenur** [comment] 2020-09-26 18:18
Duplicate of #10, is fixed in more recent versions. Look under releases in this repo.
(I need to do a pull request to azure data studio to uppdaterad the version in the store. Will happen soon)

**Closed** 2020-09-26 18:18 UTC
Labels: bug
