### ISSUE TITLE
Schema Vizualization becomes blank and must be regenerated when selecting another tab

### ISSUE THREAD

**Issue by Philgood76** [R0tenur/visualization#154] opened 2024-08-23 06:45 UTC
If you have a tab containing the **Schema Vizualisation** and select or create another tab (for exemple the content of a table), when going back to the Schema Visualization tab it appears blank and you have to generated it again (**Database + Manage + Schema Visualization**), losing the zoom and pan settings you had.

**Comment by R0tenur** [comment] 2024-08-26 11:11
Duplicate of #70

**Closed by R0tenur** 2024-08-26 11:11 UTC
Labels: bug
