### ISSUE TITLE
Mermaid failed to parse data

### ISSUE THREAD

**Issue by Lizzy151** [R0tenur/visualization#127] opened 2023-08-21 13:17 UTC
I tried using the Schema Diagram using the Schema Visualization tool in Azure Data Studio but got an error.

## Expected Behavior

It should create a database scheme diagram.

## Current Behavior

Get a parse error
Parse error on line 6622: ...lass dbo_LicencexAge-Comp-I&S { Age -----------------------^ Expecting 'NEWLINE', 'EOF', 'GENERICTYPE', 'LABEL', 'STYLE_SEPARATOR', 'STRUCT_START', 'ANNOTATION_END', 'STR', 'AGGREGATION', 'EXTENSION', 'COMPOSITION', 'DEPENDENCY', 'LINE', 'DOTTED_LINE', 'CALLBACK_NAME', 'HREF', 'UNICODE_TEXT', 'NUM', 'ALPHA', 'BQUOTE_STR', got 'MINUS'

## Steps to Reproduce

1. Install the extension 
2. Run it on the database
3.
4.

**Comment by R0tenur** [comment] 2023-08-21 13:37
Duplicate of #103 
Please provide more info

I have not been able to reproduce this, but might be because I just use sample db's
Would appreciate if someone could provide the generated md

    dissmiss alert
    export the md

**Closed** 2023-10-08 21:41 UTC
Labels: bug
