### ISSUE TITLE
Tables are shown, but 0 relations

### ISSUE THREAD

**Issue by raoulteeuwenPE** [R0tenur/visualization#60] opened 2021-08-30 12:06 UTC
1st: thank you for making this extension. Just tried it, but on the 2 db's i tried it, with one the extension only shows the tables, but (draws) 0 relations. And with the other db i have the already reported issue (hanging on getting structure). 

## Expected Behavior
Show tables and draw connections, as shown in the doc

## Current Behavior
Shows only tables, no connections, or not even the tables

## Possible Solution
Sorry, no idea

## Steps to Reproduce

1. Double click database
2. Schema Visualization is shown as option
3. Click it
4. Animation with circles is shown
5. Either it hangs or shows tables but no connections

## Context (Environment)

I was trying out this, seemingly interesting, extension

**Comment by R0tenur** [comment] 2021-09-04 12:07
To be able to investigate this I need more info about your db. The current solution is only looking at foregin keys to determine relations. Are you doing it in another way?

**Comment by raoulteeuwenPE** [comment] 2021-09-06 07:45
Thank you for the reply. Tried it on 2 db's i'm currently working with, both having tables using foreign keys. Now 1 shows relations (i think i tried this one before, not sure why it now works or what i did wrong, sorry), while the other one shows the 'busy circles' for a very long time (hasn't finished as i type this). I'm not sure when a db is assumed to be (to) 'big' for this extension; as a user only seeing the 'busy circles' animation, i have no idea what activity is going on and whether any progress is made, whether the extension is in a loop etc.

**Comment by R0tenur** [comment] 2021-09-06 19:27
Good that one of them works! 
I actually think you are experience bug #29

I will close this issue but are very happy if you could provide some info on your db since I have not been able to reproduce the issue. Is huge with hundreds of tables? In that case that could be a hint on what makes the error happen.

**Closed** 2021-09-06 19:27 UTC
Labels: bug

**Comment by raoulteeuwenPE** [comment] 2021-09-07 07:31
Not sure what the best way is to provide you with more info on the db, but it has 739 tables ;-). Btw: sorry for disturbing you on your parental leave.

**Comment by R0tenur** [comment] 2021-09-14 11:21
No worries about the parental leave, I will respond when I have the time.

That number of tables are crazy since I only have tested the extention for dbs with around 20 tables. (I'm a micro service guy) 

I'm thinking that the issue here is an timeout due to the query I have written for getting the table info, it contains a big bunch of inner selects. (You can find it in bug #29)

To revolve this I probably need to test it on a huge db or getting help by someone that has the issue.

**Comment by bruce-dunwiddie** [comment] 2021-09-14 17:39
I've submitted a PR that should significantly speed up schema queries on MSSQL, making the assumption that @raoulteeuwenPE is working on MSSQL.
